### PR TITLE
Update register command to work with 5.4

### LINKED ISSUE #31: share Method Removed
Share method is removed in laravel 5.4, please can you update the registerRefreshCommand on ServiceProvider?

$container->singleton('foo', function () {
    return 'foo';
});

https://laravel.com/docs/5.4/upgrade

### PR DESCRIPTION
**Pull request by Tlapi**
Share has been removed. So I've followed this approach:

https://laravel.com/docs/5.4/packages#commands

Fixes #31.

### CODE REVIEW

**Comment by andywer** [comment]
Hey @Tlapi. Thanks for your PR!

Looks like we might have to drop PHP 5.4 support...

**Comment by Tlapi** [comment]
Yes. And I dont see any problem with that ;-)

From 5.1 laravel requires >=5.5.9, so this would affect only 5.0 running on PHP 5.4

**Comment by andywer** [comment]
Fair enough 😉

How urgent do you need it? I would open another PR for updating the `composer.json` and `.travis.yml` to require PHP >= 5.5, but feel free to do it if you need it quickly.

**Comment by Tlapi** [comment]
Not as urgent. I would gladly wait for you PR.

Cheers.

**Comment by riskis** [comment]
Thanks @Tlapi and @andywer !!!

**Comment by andywer** [comment]
How about @alextripiq's fix #33? Any objections?

(Seems like slightly less work, since it's compatible with PHP 5.4)

**Comment by Tlapi** [comment]
No objections at all ;-)

**Comment by andywer** [comment]
Ok. Going to close this in favor of #33 then :)

**Pull request closed without merging**
