### PR TITLE
Upgrade to laravel 6.*

### PR DESCRIPTION
**Pull request by Matthijsvdorp**
This PR adds Laravel 6.0 compatibility.

### CODE REVIEW

**Comment by andywer** [comment]
Thanks, @Matthijsvdorp! Can you please check the [composer errors in CI](https://travis-ci.org/andywer/laravel-js-localization/jobs/586056147)?

**Comment by Matthijsvdorp** [comment]
Hi @andywer, I don't really understand the error messages I'm getting. Never user Mockery before. Everything passes using PHPUnit 7.5 but when using PHPUnit 8.0 some tests fail. I don't think I'll be able to fix this.

**Comment by krychu90** [comment]
Hi,
I did some research (I never used mockery) and I think you need change all _shouldReceive('getFromJson')_ to _shouldReceive('get')_ in _tests/TestCase.php_ file becouse of:
https://laravel.com/docs/6.x/upgrade#get-from-json

I hope this helps to release this update, I am waiting for it 😉

**Comment by Matthijsvdorp** [comment]
Thank you @krychu90, that did the trick!

**Comment by Matthijsvdorp** [comment]
@andywer Hi Andy, can you merge this? Thank you!

**Comment by andywer** [comment]
Ohh, of course! Have fun 👍

**Comment by krychu90** [comment]
Shouldn't it be in branch 6.0 or tagged by 6.0?

**Comment by andywer** [comment]
Yes, but I am only on my iPhone right now...

**Comment by andywer** [comment]
> Shouldn't it be in branch 6.0 or tagged by 6.0?

Done 😉

**Comment by krychu90** [comment]
Thanks, but this commit is still in 5.8 branch and will not work with laravel 5.8 (composer requires laravel 6)

**Pull request merged**
